### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by stejoo** [danielvijge/openwrt-configuration-ansible#1]
Hi,

I found out about your code on Reddit. Pretty cool and useful stuff. I am interested in trying this on my own hardware.
However I would also like to make some changes to the code, and currently --without a license-- that is not allowed. Without a license the default copyright laws apply: you retain all the rights to your work and I may not reproduce, distribute, or create derivative works from your work. So at the moment I may only view and fork (to make a copy), as per the [GitHub Terms of Service](https://docs.github.com/en/articles/github-terms-of-service).

I have a feeling you intend this code more collaborative, and perhaps even open or free (as in libre).
Please have a look at [Licensing a repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository) and/or https://choosealicense.com/ for more information.

**Comment by danielvijge** [comment]
Thanks for pointing it out. MIT licence is applied to all code with commit 821ecb765381695ce9ef984914cc0f80e51cb809

Basically, do what you want with this licence. If you do have any improvements, I do appreciate pull requests, and will look at integrating them.
