### ISSUE TITLE
Advantage of manually setting up NAS IDs

### ISSUE THREAD

**Issue by BellaCoola** [danielvijge/openwrt-configuration-ansible#2]
Hello, I am wondering, is there some advantage in setting up the NAS IDs manually? AFAIK OpenWrt sets the NAS IDs automatically, if not filled.

**Comment by danielvijge** [comment]
Not sure, to be honest. According to https://openwrt.org/docs/guide-user/network/wifi/basic#fast_bss_transition_options_80211r it's required and there is no default. But the documentation might be outdated.

**Comment by BellaCoola** [comment]
You can leave the NAS ID blank and then inspect file `/var/run/hostapd-phy<identifier>.conf`. You'll notice that the `nas_identifier` field is auto-generated from MAC address of the corresponding interface.

Also, I am wondering, why do you install `wpad-wolfssl` instead of using `wpad-basic-wolfssl`?

**Comment by danielvijge** [comment]
Might be again a bit updated, but a lot of the forum topics ([1](https://forum.openwrt.org/t/any-guide-for-802-11r/56522/4), [2](https://forum.openwrt.org/t/802-11r-fast-transition/65018/5), [3](https://forum.openwrt.org/t/802-11r-fast-transition-how-to-understand-that-ft-works/110920/26)) mention it as a requirement. However, the [package description for wpad-basic](https://openwrt.org/packages/pkgdata/wpad-basic) does mention 802.11r.

**Comment by BellaCoola** [comment]
I think that at least since version 21.02 it is included in the default `wpad-basic` package shipped with OpenWrt.

**Comment by danielvijge** [comment]
Manually setting NAS IDs has been removed in 4cce4a5737e13ad2c40b5d6faaa273c03c0d5e14
